name: build

on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.17.x"
          - "1.18.x"
          - "1.19.x"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5'
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - run: go version
      - run: rake info


      - name: Test and build package
        run: rake build


      # - name: Run tests with coverage
      #   if: matrix.os != 'windows-latest'
      #   run: go test -race -coverprofile=build/coverage.txt -covermode=atomic ./...

      # - name: Run tests without coverage (windows)
      #   if: matrix.os == 'windows-latest'
      #   run: go test -race ./...

      - name: Upload coverage
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          # fail_ci_if_error: true
          verbose: true
          flags: unittests
          file: coverage.txt

      - name: Archive action artifacts
        if: always() # Always run step even if other steps fail
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            build/release_notes.md
            build/artifacts/*
