name: build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.24.x"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Install Go
        uses: actions/setup-go@v7
        with:
          go-version: ${{ matrix.go }}

      - name: Go Version
        run: go version

      - name: Test and build package
        run: rake build

      - name: Upload coverage
        if: matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v7
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          # fail_ci_if_error: true
          verbose: true
          flags: unittests
          files: coverage.txt

      - name: Archive action artifacts
        if: ${{ !cancelled() }} # Always run step even if other steps fail
        uses: actions/upload-artifact@v7
        with:
          name: ${{ github.event.repository.name }}-${{ env.VERSION }}-${{ matrix.os }}
          path: |
            build/release_notes.md
            build/artifacts/*
