name: build

on: [push, pull_request]
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master

jobs:
  test:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        go:
          - "1.17.x"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.5'
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Check version
        run: go version

      - name: Check build info
        run: rake info

      - name: Run tests with coverage
        if: matrix.os != 'windows-latest'
        run: go test -race -coverprofile=build/coverage.txt -covermode=atomic ./...

      - name: Run tests without coverage (windows)
        if: matrix.os == 'windows-latest'
        run: go test -race ./...

      - name: Upload coverage
        if: matrix.os != 'windows-latest'
        uses: codecov/codecov-action@v3
        with:
          # token: ${{ secrets.CODECOV_TOKEN }}
          # fail_ci_if_error: true
          verbose: true
          flags: unittests
          file: coverage.txt
