name: release
on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.5'
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - run: go version
      - run: rake info
      - run: git status

      - name: Test and build package
        run: rake build

      # - name: Archive action artifacts
      #   if: always() # Always run step even if other steps fail
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: artifacts
      #     path: |
      #       build/release_notes.md
      #       build/artifacts/*

    - name: Upload artifacts to release
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      uses: ncipollo/release-action@v1
      with:
        artifacts: "build/artifacts/*"
        bodyFile: "build/release_notes"
        token: ${{ secrets.GITHUB_TOKEN }}
